### ISSUE TITLE
Domain http://simplelineicons.com is expired?

### ISSUE THREAD

**Issue by lockevn** [thesabbir/simple-line-icons#108]
Visit http://simplelineicons.com, you will see Namecheap screen, not Simple Line Icons preview.

**Comment by kuwaitbinary** [comment]
Right now i am using archived version

https://web.archive.org/web/20180724133539/http://simplelineicons.com/

**Comment by jstnmthw** [comment]
This seem to happens quite often. Why not just switch to github hosted?

**Comment by baba43** [comment]
Yes, please do it.. lol

**Comment by ikariwill** [comment]
> This seem to happen quite often. Why not just switch to github hosted?

Someone did this: https://simplelineicons.github.io/

**Comment by Sowed** [comment]
> Someone did it: https://simplelineicons.github.io/
Why not update the link in the readme to that?
