### ISSUE TITLE
Syntax error in simple-line-icons/scss/simple-line-icons.scss

### ISSUE THREAD

**Issue by mvastola** [thesabbir/simple-line-icons#11]
Hi,
The Sass gem in Ruby doesn't seem to like the syntax of `simple-line-icons/scss/simple-line-icons.scss`.

I'm getting the following error on Rails:
![action_controller_exception_caught_-_2015-02-14_09 53 12](https://cloud.githubusercontent.com/assets/599767/6199966/73537cb6-b42f-11e4-935a-c6310a9c76be.png)

The suspect code seems to be:
````
.#{$simple-line-icon-prefix} {
  &user-female, &user-male {
    /* CSS rules go here */
  }
}
````

By my reading, sass seems to not like the `&user-female` syntax.

Thanks for your help.

**Comment by thesabbir** [comment]
@mvastola I am not familiar with scss.
@zeshanshani added scss support & I hope he can help.

**Comment by zeshanshani** [comment]
Hi @mvastola, 

This should work in Sass 3.3.0 version (<a href="http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#330_7_march_2014">Sass Changelong</a>):

<blockquote> The parent selector, &, can be used with an identifier suffix. For example, &-suffix and &_suffix are now legal. The suffix will be added to the end of the parent selector, and will throw an error if this isn’t possible. & must still appear at the beginning of a compound selector – that is, .foo-& is still illegal. </blockquote>

However, I'll update the code for maximum compatibility. 

Thanks!

**Comment by mvastola** [comment]
Oh. Oops. I had my sass-rails gem locked at too low a version, I guess. Fixed!
Thanks.

**Comment by zeshanshani** [comment]
Cool.
