### ISSUE TITLE
Domain is for sale?

### ISSUE THREAD

**Issue by Tictac0723** [thesabbir/simple-line-icons#110]
I can't check the different icons because your domain is down.

**Comment by OleJack** [comment]
https://simplelineicons.github.io/

**Comment by praveenscience** [comment]
It's now up in the GitHub pages instead.

**Comment by andrewb273** [comment]
@praveenscience can you update the URL in the repository page title? Currently it's `Simple and Minimal Line Icons http://simplelineicons.com`.
