### ISSUE TITLE
Error: Cannot find module 'less'

### ISSUE THREAD

**Issue by nileshbhingaradiya** [thesabbir/simple-line-icons#114]
when I try to build my project I got this error "Error: Cannot find module 'less'"

error /codebuild/output/src517253156/src/node_modules/simple-line-icons: Command failed.
--
265 | Exit code: 1
266 | Command: node scripts/build
267 | Arguments:
268 | Directory: /codebuild/output/src517253156/src/node_modules/simple-line-icons
269 | Output:
270 | internal/modules/cjs/loader.js:638
271 | throw err;
272 | ^
273 |  
274 | Error: Cannot find module 'less'
275 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
276 | at Function.Module._load (internal/modules/cjs/loader.js:562:25)
277 | at Module.require (internal/modules/cjs/loader.js:692:17)
278 | at require (internal/modules/cjs/helpers.js:25:18)
279 | at Object.<anonymous> (/codebuild/output/src517253156/src/node_modules/simple-line-icons/scripts/less2css.js:1:14)
280 | at Module._compile (internal/modules/cjs/loader.js:778:30)
281 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
282 | at Module.load (internal/modules/cjs/loader.js:653:32)
283 | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
284 | at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by thesabbir** [comment]
Fixed - please use version 2.5.2

**Comment by thesabbir** [comment]
#3fcc655
