### ISSUE TITLE
Add !default on SCSS variables

### ISSUE THREAD

**Issue by garbinmarcelo** [thesabbir/simple-line-icons#116]
Add !default to SCSS variables so they can be subscribed to.

**Comment by jrubins** [comment]
It seems like @garbinmarcelo and I were both experiencing the same problem and both opened pull requests at the same time. Just wanted to link my PR to this issue as well so we can make sure to deal with both of them! #117

**Comment by thesabbir** [comment]
Resolved by #117 

Thanks to @jrubins

**Comment by jrubins** [comment]
@thesabbir I see that there was a new release (`v2.5.4`) but it looks like it was for githash ccba29d, which doesn't include the changes from my merged PR. Do you mind crafting another release so we can get those SASS default fixes?

**Comment by thesabbir** [comment]
@jrubins missed that part.
v2.5.5 is available now
