### ISSUE TITLE
Did the structure changed?

### ISSUE THREAD

**Issue by fernan256a** [thesabbir/simple-line-icons#119]
Hello!

I have a react js project with version 2.4.1 since some days ago compilation started failing because the structure looks different!
I check your package.json and I don't understand why is downloading v2.5.2

Any idea?

**Comment by sh-developers** [comment]
Yes the structure has changed in a minor version, could you revert this change @thesabbir ? It would be better for automated builds everywhere if those things would not change in a minor version bump.
The path changed from `~simple-line-icons/scss/simple-line-icons` to `~simple-line-icons/dist/styles/simple-line-icons`

**Comment by rnwolfe** [comment]
100% agree, I just spent hours troubleshooting why my build was suddenly failing with no changes.

**Comment by thesabbir** [comment]
Added backward compatibility for 2.X
