### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by yrezgui** [thesabbir/simple-line-icons#12]
Hi Sabbir,

Can you add the support by adding a package.json and publishing the project on NPM.
It's not a big deal but I stopped using bower and having it on NPM avoid me to have two dependencies manager.

Thanks man :)

**Comment by thesabbir** [comment]
@yrezgui published on npm.
checkout https://www.npmjs.com/package/simple-line-icons

**Comment by yrezgui** [comment]
Thanks man :)

**Comment by thesabbir** [comment]
@yrezgui no problem.
BTW nice website :)
