### ISSUE TITLE
add icons to set

### ISSUE THREAD

**Issue by govza** [thesabbir/simple-line-icons#14]
Hi, thank you for greate work! 
I have a question, - is there easy way to add these icons to set, with apps like fontello or icomoon without changing default names and chars.
 If I import existing font it generates new names such as glyph1-icon, glyph2-icon and etc. Or could you provide separate svg files with names (icon-rocket, icon-phone). Thank you. 
P.S. skype icon will be very appreciated

**Comment by thesabbir** [comment]
Thanks!
@govza I am not the author of the font. I packaged it for ease of use in web projects. So I have no idea on how to add new fonts. I hope you've got my point.

**Comment by fjcero** [comment]
@govza there is some way to keep improving this icon set? I don't have experience with webfonts, but that things could be learned. I need some icons, I like this pack a lot.
