### ISSUE TITLE
Google+ icon Update

### ISSUE THREAD

**Issue by mruz** [thesabbir/simple-line-icons#16]
I miss g+ icon, any chance to add?

**Comment by minhluan259** [comment]
+1

**Comment by thesabbir** [comment]
Added in new version

**Comment by mruz** [comment]
Thanks!

**Comment by mruz** [comment]
Did you see new google+ logo? :smile: 
![G+](https://ssl.gstatic.com/images/branding/google_plus/2x/gplus_icon_flatsq_44dp.png)

**Comment by thesabbir** [comment]
@ahmadfiroz new google icon is cool.
@mruz we'll update it in next release :)

**Comment by ahmadfiroz** [comment]
will work on a hotfix asap @thesabbir

**Comment by praveenscience** [comment]
@ahmadfiroz Any updates on this? :)

**Comment by ahmadfiroz** [comment]
@praveenscience you can try adding. I used icomoon free versions but wasn't able to find that projects later on. if you have better glyph mapping please do make the g+ icon

**Comment by praveenscience** [comment]
@ahmadfiroz I am not sure. New to me. I am just a Front End Architect. But lemme try with Icomoon. I can make that in SVG, but not sure if it is possible to make it inside a font.

**Comment by praveenscience** [comment]
@thesabbir Can you add me as a collaborator buddy?

**Comment by thesabbir** [comment]
@praveenscience done.

**Comment by mruz** [comment]
I think in 2.3.0 G+ is smaller than other icons. What do you think to remove + and left only G, because it's too wide. We can rename it to social-google. Can I become your collaborator?

**Comment by thesabbir** [comment]
@mruz yes, you are welcome.
