### ISSUE TITLE
Add Woff2 format

### ISSUE THREAD

**Issue by mruz** [thesabbir/simple-line-icons#20]
Please, add woff2 format.

> The new WOFF 2.0 Web Font compression format offers a 30% average gain over WOFF 1.0 (up to 50%+ in some cases). WOFF 2.0 is available since Chrome 36 and Opera 23.

Gist (from ttf -> woff2): https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a
W3C spec: http://www.w3.org/TR/WOFF2/

**Comment by thesabbir** [comment]
#21

**Comment by mruz** [comment]
Works like a charm, nice compression for newer webbrowser:
```
woff1 53.444 kB
woff2 26.384 kB
```

Thanks!

**Comment by thesabbir** [comment]
@mruz thanks :)
