### ISSUE TITLE
Search functionality in docs

### ISSUE THREAD

**Issue by thesabbir** [thesabbir/simple-line-icons#25]

**Comment by praveenscience** [comment]
I can contribute for this. :+1: May I?

**Comment by praveenscience** [comment]
Hi, #39 will fix this. Let me know if this helps you. :+1:

**Comment by praveenscience** [comment]
You can check out a [live demo](http://praveenscience.github.io/simple-line-icons/).

**Comment by thesabbir** [comment]
Thanks :)
