### ISSUE TITLE
updated icons not in npm?

### ISSUE THREAD

**Issue by johnnybell87** [thesabbir/simple-line-icons#26]
Hey, 

I noticed that there are some new icons such as the arrow-down instead of the arrow-down-circle. 

I wish to use that new arrow-down... how do I update my npm to have the latest files?

Thanks. 

JB

**Comment by thesabbir** [comment]
Forgot to publish the new version on npm. [resolved]

Update version number on your package json:
```
"dependencies": {
     simple-line-icons: ^2.2.1
```
and then :
```
npm i simple-line-icons --save
```

**Comment by johnnybell87** [comment]
Hey mate, 

Thanks for that.. I'm still getting an error though:

ERROR in ./~/simple-line-icons/fonts/Simple-Line-Icons.eot?-i3a2kk
Module parse failed: /PATH/node_modules/simple-line-icons/fonts/Simple-Line-Icons.eot?-i3a2kk Line 1: Unexpected token ILLEGAL

**Comment by thesabbir** [comment]
When do you exactly got this error?

**Comment by johnnybell87** [comment]
I'm using webpack I'll figure it out.

**Comment by thesabbir** [comment]
@johnnybell87 have you fixed your webpack error?

**Comment by johnnybell87** [comment]
Yeah mate, got it sorted, wasn't loading the EOT with the ? after it properly. 

Thank you
