### ISSUE TITLE
Improve new icons

### ISSUE THREAD

**Issue by furyscript** [thesabbir/simple-line-icons#27]
Hi,

This icons are very amazing rather then font awesome, can you implement more icons?

**Comment by thesabbir** [comment]
@furyscript please mention icon names. We'll try to implement them in next version.

**Comment by furyscript** [comment]
Well, take idea from font-awesome... This package is nice for slim line icon and well designed...

There is some internet site with a lot of icons :)

For example I sold out all "book" icons for my sections

**Comment by thesabbir** [comment]
I am not a designer myself. New icons are welcome from designers.

**Comment by hedii** [comment]
maybe the original designer is okay to produce more icons: https://twitter.com/byjml

**Comment by mlemmers** [comment]
Hi, I'm actually missing a simple "cross" icon. Like the "delete" but without the circle around it.

**Comment by thesabbir** [comment]
more like a 'X' ? @mlemmers

**Comment by thesabbir** [comment]
yeah, current one has circle around it.

**Comment by mlemmers** [comment]
@thesabbir yes just a regular "x" I guess. To replace the hamburger icon when activated and to use on modals etc.

**Comment by thesabbir** [comment]
@mruz is doing a great job with extending icons. I think he can help :)

**Comment by mlemmers** [comment]
@thesabbir @mruz great to hear! It wouldn't actually be a bad thing to have all those icons (+, -, x) without the circle as well.

**Comment by praveenscience** [comment]
That should be &times; and not `x`. :D

**Comment by mlemmers** [comment]
@praveenscience haha yes, didn't even know there was a keyboard shortcut for that one!

**Comment by mruz** [comment]
What's wrong with those in the circle? :smile:

**Comment by praveenscience** [comment]
@mlemmers Na... I used `&times;` Unfortunately no keyboard shortcuts... :(

**Comment by mlemmers** [comment]
@mruz absolutely nothing wrong! It's just not always desirable in some designs ;)
@praveenscience aah okay!

**Comment by thesabbir** [comment]
closed due to inactivity. feel free to open a new issue.
