### ISSUE TITLE
Typo in class name

### ISSUE THREAD

**Issue by liamtarpey** [thesabbir/simple-line-icons#35]
```.icon-drawar``` should be  ```.icon-drawer ```

:) 

Thanks

**Comment by thesabbir** [comment]
@liamtarpey well thats just silly :package:  :)

**Comment by letalumil** [comment]
I guess the same for `.icon-symble-female`. It should be `.icon-symbol-female`?

**Comment by thesabbir** [comment]
Fixed. Please use the latest version :)

**Comment by letalumil** [comment]
Thanks for the fix!
 
I think it's reasonable to keep the typo classes for backward compatibility. Or use [semver](http://semver.org/) approach: bump MINOR number instead of PATCH number. Because you can imagine, that after the update those who used  'typo' classes would have their code/app broken.
