### ISSUE TITLE
Something wrong on mobile

### ISSUE THREAD

**Issue by neilliang** [thesabbir/simple-line-icons#36]
Hi, 
I love this font so much, but I can't use it if I put it in my own server.
It preforms perfectly when I use cdnjs way to do it. Once I download it(zip) and put in my server, the icon has wrong display on mobile device(PC is fine). Did I miss something?

Iphone6s plus ios 9.2
![default](https://cloud.githubusercontent.com/assets/1026331/12256252/e1ff973c-b936-11e5-8224-8b4e844b79e5.PNG)

My server info:
Rails 4.2.3

Sorry about my English.

Josh

**Comment by thesabbir** [comment]
Hi @neilliang  I could not recreate your issue. 
What browser is you using? Have you checked your media queries?  Use should try remote debugging with chrome. Let me know.

**Comment by thesabbir** [comment]
@neilliang I think it's not the issue with package itself.

**Comment by neilliang** [comment]
@thesabbir  Thank you for your reply.
I tried safari and chrome, I got same result. I also put the package on different places, my own machine and AWS S3, still got error icons. Do I need to do any setting on server? I will try remote debugging and show you what happens.
