### ISSUE TITLE
Cheatsheet in docs

### ISSUE THREAD

**Issue by caiocaladoo** [thesabbir/simple-line-icons#38]
Hi there, 

Your repository is great and thank you for your contribution! I really love the idea of having a package like this and being able to download/install it! 

I'd like to suggest a cheatsheet to copy/paste your icons on my design files (.ai, .psd, etc.). Right now, I'm not able to solve this (or at least I don't know how to). 

It is something like this https://fortawesome.github.io/Font-Awesome/cheatsheet/ 

Thanks :smile:

**Comment by fuecisla** [comment]
Yeah... I`m lost too. Obviously is my fault not knowing how to use these icons. It would have been great if you could put a link to a how-to on the net. Those in need of help are the most grateful usually :)

Cheers,

**Comment by fuecisla** [comment]
maybe this?...[https://css-tricks.com/html-for-icon-font-usage/]

**Comment by fitodac** [comment]
I create a creative cloud library http://adobe.ly/2bQ48wl to use with Ai or Ps. :)

**Comment by thesabbir** [comment]
@fitodac nice!
