### ISSUE TITLE
bower simple-line-icons#2.2.x invalid-meta The "main" field cannot contain font, image, audio, or video files

### ISSUE THREAD

**Issue by Codermar** [thesabbir/simple-line-icons#46]
In my Jenkins build I am getting this reported as error.
bower simple-line-icons#2.2.x     invalid-meta The "main" field cannot contain font, image, audio, or video files

Are the fonts necessary in the main definition? 
Because the automation will install via bower, I can't manually change the main definition for that file.

Please advice.

Thanks.

**Comment by thesabbir** [comment]
Looks like bower specs changed by bower/spec#43
Will fix is asap.

Thanks
