### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by neeltjechanterie** [thesabbir/simple-line-icons#49]
Why is your search bar gone!
I'm loving the icons, such a bummer I can't search anymore ...

**Comment by praveenscience** [comment]
Oh yeah, even I noticed that. Lemme fix it off. :)

**Comment by neeltjechanterie** [comment]
Thanks! 😄

**Comment by thesabbir** [comment]
search was not in the generator file. when I generated new doc it was gone.
:(

**Comment by praveenscience** [comment]
Fixed it. :+1:

**Comment by neeltjechanterie** [comment]
Awesome! Thanks for the quick replies!

**Comment by praveenscience** [comment]
You are welcome! :)

**Comment by thesabbir** [comment]
Thanks @praveenscience

 We generate docs automatically with [this file](/thesabbir/simple-line-icons/blob/gh-pages/genarate.php)
```
php genarate.php > index.html
```
So changing index.html is not effective if we generate docs for new icons.

**Comment by praveenscience** [comment]
@thesabbir I'll take care of it as well... ;)
