### ISSUE TITLE
Update instagram icon

### ISSUE THREAD

**Issue by thesabbir** [thesabbir/simple-line-icons#51]
new icon:

![](https://5a5a57ff32a328601212-ee0df397c56b146e91fe14be42fa361d.ssl.cf1.rackcdn.com/icon/instagram_logos_glyph/03H5cHNMt-Jni4pe9u+7/glyph-logo_May2016_200.png)

**Comment by mruz** [comment]
Do we need a new icon? We have similar social-instagram or camera

**Comment by mruz** [comment]
OK, I'll deal with this https://www.instagram-brand.com

**Comment by thesabbir** [comment]
Thank you :)
