### ISSUE TITLE
Icon google not working

### ISSUE THREAD

**Issue by StevenLantinga** [thesabbir/simple-line-icons#53]
I did a npm install and all icons are working except the google icon.

**Comment by thesabbir** [comment]
updated package. please check now.

**Comment by StevenLantinga** [comment]
That's fast. But I don't see any changes yet. Maybe I'm missing something but you're last commit is from 6 days ago. Am I on the wrong branche?

**Comment by thesabbir** [comment]
try reinstalling the package.

**Comment by StevenLantinga** [comment]
Already did that. No changes yet.

**Comment by mruz** [comment]
Since 2.3.1 version https://github.com/thesabbir/simple-line-icons/commit/315e39f1722b679fb648f828a422e69373649dfe there is no `gplus`, just `google`. Maybe this is the reason.
```html
<i class="icon-social-google"></i>
```

**Comment by thesabbir** [comment]
@mruz thanks for pointing that out.
I think we should follow "semver" closely. Breaking changes should be introduced in major versions.

**Comment by StevenLantinga** [comment]
It appears to be working now. Maybe cache. Thanks.
