### ISSUE TITLE
Please create VK icon

### ISSUE THREAD

**Issue by dimasaenko** [thesabbir/simple-line-icons#56]
Hi, 

we love your icons and regularly use them on our projects.

Please create VK icon for us.

Thanks a lot :)

**Comment by praveenscience** [comment]
@dimasaenko Do you have an SVG icon in mind?

**Comment by thesabbir** [comment]
This one is a good starting point:

![](https://cdn3.iconfinder.com/data/icons/rcons-social/32/vkontakte-512.png)

Source: Icon finder

**Comment by fitodac** [comment]
what about a vk logo without the square?

**Comment by mruz** [comment]
Will be too in the next release.

Sent from my HTC

----- Reply message -----
