### ISSUE TITLE
Icon request: events icon

### ISSUE THREAD

**Issue by Marchrius** [thesabbir/simple-line-icons#57]
Very similar to calendar icon.

An example from material-icon:

https://design.google.com/icons/#ic_event

**Comment by thesabbir** [comment]
We are open to include any new icon request. However, I don't see much difference between our calendar icon and your suggested "event" icon. Can you add some reason why should add "event" icon?

@mruz what do you think?

**Comment by mruz** [comment]
I think we don't need a large sets of icons like fontawsome, just basic, simple icons. @Marchrius do you need both icons (calendar, event) or event would be better for you?

**Comment by Marchrius** [comment]
@thesabbir You are right, they are very similar but is the only example I found. A calendar icon is an icon that rapresents all the calendar so the art is like a grid. An event icon is a blank calendar (w/o grid) with a specific spot selected.

@mruz Both of the icons. I'm not looking for a collection that has a lot of icons but a collection with icons used in web apps. I have a web app with both calendar and events with different functionalities and I need different icon. If I can help feel free to ask me for help.

**Comment by mruz** [comment]
OK, thanks. I'll try to add it.
