### ISSUE TITLE
More infos about this project

### ISSUE THREAD

**Issue by marchrius** [thesabbir/simple-line-icons#58]
Do you want this library is an alternate library or a complementary part?

**Comment by thesabbir** [comment]
@Marchrius alternate library or a complementary of other icon fonts?

**Comment by Marchrius** [comment]
Yes, like font-awesome.

**Comment by illyon** [comment]
Can I use this font in my website without contribution like font awesome?

**Comment by illyon** [comment]
Can I use this font in my website without attribution or reference to the author like font awesome?

**Comment by thesabbir** [comment]
yes you can @illyon
