### ISSUE TITLE
have preview page of the icons 

### ISSUE THREAD

**Issue by sinsunsan** [thesabbir/simple-line-icons#7]
when I go to http://graphicburger.com/wp-content/uploads/2013/10/Simple-Line-Icons-Webfont-600.png
I am not able to make the relation between the icon and it's name 
would be very useful to have a preview with name similar that http://fortawesome.github.io/Font-Awesome/icons/
Or how do you do to choose you icons ?

**Comment by thesabbir** [comment]
Will be documented soon :)

**Comment by bbraga** [comment]
This is not supposed to be pretty or DRY, it was just to scratch an itch.

- icons.php
```PHP
<?php
    $css = './web/components/simple-line-icons/css/simple-line-icons.css';
?>
<html>
<head>
    <link rel="stylesheet" href="<?php echo $css; ?>">
</head>
<body>
<?php
$pattern = '/\.(icon-(?:\w+(?:-)?)+):before\s+{\s*content:\s*"(.+)";\s+}/';
$css_file = file_get_contents($css);
preg_match_all($pattern, $css_file, $icons, PREG_SET_ORDER);
foreach($icons as $icon){
    echo '<i style="font-size: 30px;" class="'.$icon[1].'"></i> ==> '.$icon[1].'<br>';
}?>
</body>
</html>
```

```BASH
$ php icons.php > icons.html
```

load icons.html on your browser, and visualize

**Comment by thesabbir** [comment]
@bbraga thanks for the scratch an itch.

A preview with icon & class name is available now.
http://thesabbir.github.io/simple-line-icons

**Comment by thesabbir** [comment]
@sinsunsan more suggestion is welcome :)
