### ISSUE TITLE
Domain name issue

### ISSUE THREAD

**Issue by tommymcdonald** [thesabbir/simple-line-icons#85]
On the documentation site, I'm seeing that there may be a registration issue:

![screen shot 2017-09-21 at 9 29 32 am](https://user-images.githubusercontent.com/3039547/30701277-7c87f13c-9eaf-11e7-80da-f80686bdf783.png)

**Comment by 3ncor3** [comment]
yeah, face it too.. please revive...

**Comment by DennisGuo** [comment]
The domain is Expired!!!

**Comment by Hirbod** [comment]
WTF...
<img width="1343" alt="bildschirmfoto 2017-09-25 um 00 50 36" src="https://user-images.githubusercontent.com/504909/30787546-826c9272-a18b-11e7-9273-08f7f493a9a7.png">

**Comment by kyoyadmoon** [comment]
fork it, and delete the CNAME file in `gh-pages` branch
then you can use it on https://YOUR_GITHUB_USERNAME.github.io/simple-line-icons/
or you can use mine
https://kyoyadmoon.github.io/simple-line-icons/

**Comment by ngstwr** [comment]
I tried contacting Sabbir but emails on his id are bouncing, so far I haven't found any other way to contact him.

**Comment by neeltjechanterie** [comment]
Thanks @kyoyadmoon ! 
@ngstwr Have you tried to contact one of the contributors?

**Comment by tommymcdonald** [comment]
Since this appears to be fixed, I'm going to go ahead and close this ticket out.

**Comment by tommymcdonald** [comment]
I was mistaken.

**Comment by cassianomon** [comment]
https://simplelineicons.github.io/simplelineicons/

**Comment by cassianomon** [comment]
What you guys think? https://github.com/thesabbir/simple-line-icons/issues/97

**Comment by thesabbir** [comment]
#113
