### ISSUE TITLE
This Domain Name Has Expired - Renewal Instructions.

### ISSUE THREAD

**Issue by neeltjechanterie** [thesabbir/simple-line-icons#87]
Preview site (http://simplelineicons.com/) not available any more, since a few weeks now ...

**Comment by faahmad** [comment]
+1

**Comment by erayaydin** [comment]
:+1:

**Comment by neeltjechanterie** [comment]
Duplicate of #85

**Comment by tommymcdonald** [comment]
@neeltjechanterie I just checked and the domain name appears to be renewed. I'm going to close my initial request (#85).

**Comment by cassianomon** [comment]
What you guys think? https://github.com/thesabbir/simple-line-icons/issues/97

**Comment by thesabbir** [comment]
#113
