### ISSUE TITLE
simplelineicons.com is down

### ISSUE THREAD

**Issue by adrianlee** [thesabbir/simple-line-icons#90]
This site can’t be reached

simplelineicons.com’s server DNS address could not be found.

**Comment by gedeagas** [comment]
@adrianlee I think the domain is suspended because the site owner doesn't submit the ICANN verification code

**Comment by Oldenborg** [comment]
Subscribed to get notified when this is fixed

**Comment by lookitsatravis** [comment]
Cached version which lists out all of the icon classes (though, unfortunately you can't view them):

http://cc.bingj.com/cache.aspx?q=url%3ahttp%3a%2f%2fsimplelineicons.com%2f&d=5044719911372892&mkt=en-US&setlang=en-US&w=_5SisZudYiT2EtsiP6-8GyBQ6MOE71KM

**Comment by Oldenborg** [comment]
Find the icons here https://kyoyadmoon.github.io/simple-line-icons/ thanks to @kyoyadmoon

**Comment by ntdvl** [comment]
I hope, the web site will go online.

**Comment by k3davis** [comment]
Issue appears to be resolved.

**Comment by cassianomon** [comment]
What you guys think? https://github.com/thesabbir/simple-line-icons/issues/97

**Comment by thesabbir** [comment]
#113
