### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by Moedella** [thesabbir/simple-line-icons#95]
Is there any cheat sheet for the font .. How can we use it in the design phase in Sketch,Photoshop or Illustrator?

**Comment by SebCodesStuff** [comment]
I really wish the documentation had even a single example. I'd love to use the package but have no idea what to do.

**Comment by arielmorry** [comment]
1. install ttf on windows
2. open Photoshop
3. open from top menu Window > Glyphs
4. search for the simple-line-icons in fonts dropdown list
5. Text tool >> click anywhere
6. Double click the glyph from the Glyphs Window

This will insert the icon into the document.

**Comment by twnaing** [comment]
For cheatsheet,

Coder: index.html page in gh-pages branch has the cheatsheet

Non-coder: try this https://jsfiddle.net/twnaing/6q0j8pyh/1/

For design phase, look @arielmorry [response](https://github.com/thesabbir/simple-line-icons/issues/95#issuecomment-396899047)
