### ISSUE TITLE
Create simplelineicons organization since this repository is not maintained anymore

### ISSUE THREAD

**Issue by cassianomon** [thesabbir/simple-line-icons#97]
What you guys think of giving all the feedbacks, issues and PR for a centralized repository inside a organization?

I created [Simplelineicons Organization](https://github.com/simplelineicons) and we could keep the work going on there

**Comment by tabuna** [comment]
Hi @cassianomon I'm also concerned about continuing to work on these icons.
We collected all the original [SVG](https://github.com/orchidsoftware/icons/tree/master/src/svg) files and begin to [draw new icons](https://github.com/orchidsoftware/icons/issues/1). If you have a desire to help, then we will do it together!

**Comment by cassianomon** [comment]
Would you mind to create the organization? Since the community of this library is not very interested in helping it grow

**Comment by thesabbir** [comment]
#113
